/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etsaplicaciones;

import etsaplicaciones.filefinderserver.FileFinderClient;
import etsaplicaciones.filefinderserver.FileFinderServer;
import etsaplicaciones.filefinderserver.IFindFileResponse;
import etsaplicaciones.multicastserver.MulticastServer;
import etsaplicaciones.searchserver.IServerAvailable;
import etsaplicaciones.searchserver.ServerAvailable;
import etsaplicaciones.searchserver.ServerHandler;
import java.util.ArrayList;

/**
 *
 * @author Marco
 */
public class MainFrame extends javax.swing.JFrame implements IServerAvailable, IFindFileResponse {

    /**
     * Creates new form Main
     */
    public MainFrame() {
        initComponents();
    }
    
    public void setPort(int port){
        this.port = port;
        jLabel2.setText("" + port);
        initMulticast();
        initFileFinderServer();
    }
    
    private void initFileFinderServer(){
        fileFinderServer = new FileFinderServer(port, serverHandler.getNext());
        try{
            fileFinderServer.startListening();
        }catch(Exception e){
        }
    }
    private void askForFile(){
        String fileName = jTextField1.getText();
        fileFinderClient = new FileFinderClient(serverHandler.getNext(), this);
        try{
            fileFinderClient.askForFile(fileName);
        }catch(Exception e){
        }
    }
    
    private void initMulticast(){
        MulticastServer multicastServer = new MulticastServer(ipGroup, port, portGroup);
        multicastServer.startSending();
        
        serverHandler = new ServerHandler(portGroup, port, ipGroup, this);
    }
    
    private String getServersString(ArrayList<ServerAvailable> servers){
        String value = "";
        for(int i = 0; i < servers.size(); i++){
            value += servers.get(i).ID + "\n";
        }
        return value;
    }
    
    private void notifyMessage(String message){
        this.message += message;
        jTextPane1.setText(this.message);
    }
    
    @Override
    public void ListHasBeenUpdated(ArrayList<ServerAvailable> servers, ServerAvailable previous, ServerAvailable next) {
        if(this.previous != previous){
            if(this.previous != null){
                notifyMessage("El nodo previo ha cambiado de " + this.previous.ID + " a " + previous.ID + "\n");
            }
            this.previous = previous;
        }
        if(this.next != next){
            if(this.next != null){
                notifyMessage("El nodo siguiente ha cambiado de " + this.next.ID + " a " + next.ID + "\n");
            }
            this.next = next;
        }
        
        jTextPane2.setText(getServersString(servers));
        jLabel7.setText(previous.ID);
        jLabel9.setText(next.ID);
    }
    
    @Override
    public void findFileResponse(String message) {
        jTextPane3.setText(message);
    }
   
    private int port = -1;
    private String ipGroup = "228.1.1.1";
    private int portGroup = 8020;
    private ServerHandler serverHandler;
    private FileFinderServer fileFinderServer;
    private FileFinderClient fileFinderClient;
    private ServerAvailable previous;
    private ServerAvailable next;
    
    private String message = "";
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Título");

        jLabel1.setText("Puerto:");

        jLabel2.setText("XXXX");
        jLabel2.setName("lblPort"); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(37, 16));

        jLabel3.setText("Eventos");

        jScrollPane1.setViewportView(jTextPane1);

        jLabel4.setText("Servidores");

        jScrollPane2.setViewportView(jTextPane2);

        jLabel5.setText("Buscar Archivos");
        jLabel5.setToolTipText("");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jTextPane3);

        jLabel6.setText("Nodo Anterior:");

        jLabel7.setText("????");

        jLabel8.setText("Nodo Siguiente:");

        jLabel9.setText("????");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addGap(0, 230, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        askForFile();
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables

}
